### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by superKlaver-nl** [ugurkocde/IntuneOffboarding#1] opened 2023-07-18 08:41 UTC
I have tried the IntuneOffboarding tool. Modules are installed and succesfully connected. Searched in the Intune portal for a device name, copied the device name and paste into to IntuneOffboarding tool. Message: please ensure device name is valid. 

There is also no sign-off button to test in another tenant. IntuneOffboarding tool keeps succesfully connected to the same tenant after closing the tool.

![Offboard](https://github.com/ugurkocde/IntuneOffboarding/assets/97507981/c6dc2289-954d-42a9-a075-a99a62953ae2)

**Comment by superKlaver-nl** [comment] 2023-07-18 08:54
After updating the Graph modules, the search worked.

**Comment by AleschaP** [comment] 2023-07-18 12:04
I'm having the same issue, I've updated the modules and still getting this issue

**Comment by Dez-Informatyk** [comment] 2023-07-18 18:24
Hi,
I have a similar problem - I can't delete the device. The tool found my device and show its status, but in all cases, I get the same message - "Error in offboarding operation. Please ensure device name is valid".
![IntuneOffboarding](https://github.com/ugurkocde/IntuneOffboarding/assets/102084604/fb6ac9f6-f6f9-448b-854d-c518e2d08075)

**Comment by ugurkocde** [comment] 2023-07-18 20:55
Hey guys, I will be adding a logging functionality so you will have a better understanding of the error. Please understand that I dont know your environment and troubleshooting it for you is hard. I will be creating a short quide that could help you to find the error but this will happen tomorrow.

**Comment by thiagobeier** [comment] 2023-07-19 04:18
I'm getting the following error.
WARNING: Selected Microsoft Graph profile 'v1.0' does not exist for module 'Microsoft.Graph.DeviceManagement.Enrollment
'. No cmdlets were loaded.

After running each line from the Get-IntuneOffboardingTool.ps1 manually I found that some environments might have the Microsoft known issue for Hybrid Azure AD joined (duplicated device names) where SAME DEVICE has 02 objects (one Hybrid Azure AD joined 'created after device is created in ADDS and synced over to Azure AD' and another Azure AD joined 'crated during windows autopilot device hash registration'). Therefore, that'd required some logic to identify the INTUNE object by its Intune Managed Device ID and Azure AD ID as in here (https://thiagobeier.wordpress.com/2023/06/01/how-to-track-device-objects-in-intune/)

**Comment by thiagobeier** [comment] 2023-07-19 05:05
another finding
Get-MgDeviceManagementWindowsAutopilotDeviceIdentity
WARNING: Selected Microsoft Graph profile 'v1.0' does not exist for module 'Microsoft.Graph.DeviceManagement.Enrollment
'. No cmdlets were loaded.

then I replaced $AutopilotDevice = Get-MgDeviceManagementWindowsAutopilotDeviceIdentity -Filter "contains(serialNumber,'$($IntuneDevice.SerialNumber)')" -ErrorAction Stop
by
$AutopilotDevice = **Get-AutopilotDevice | Where-Object {$_.serialNumber -eq "$($IntuneDevice.SerialNumber)"} -ErrorAction Stop**

got it working running by chunks 
if we try to DELETE Azure AD device before Intune Device Azure AD object remains in AAD
if we remove INTUNE object before Azure AD object it goes fine 

I've seen environments with the following:
- One Serial number for several different Intune Windows devices (different names)
- One Serial number for several different Intune macOS devices (different names)
- Device "A" duplicated in Azure AD and only one VALID device Name in Intune based on AzureAD ID and OnPremGUID (for hybrid ad joined) and Azure AD ID with Intune device ID for Azure AD joined only , if we INVERT the logic (search by serial number) it will exists in Intune regardless if it's an autopilot registered device or not then we'll match with existing Azure AD objects and DELETE it order (autopilot, intune, azure ad and for HAADJ connect to domain controller search and delete device in local AD)
- Autopilot (only accepts one SERIAL number, so there device either exists or not)

**Comment by ugurkocde** [comment] 2023-07-19 17:37
Version 2 is live. Please test it and also check the log for potential errors.

**Comment by Dez-Informatyk** [comment] 2023-07-19 18:34
Hello :)
Wow, nice work with new options :)
That's my logs:
2023-07-19 20:29:24 - Window is loading...
2023-07-19 20:29:25 - Not connected to MS Graph
2023-07-19 20:29:25 - Window is loading...
2023-07-19 20:29:26 - Modules already installed.
2023-07-19 20:29:42 - Authentication Successful
2023-07-19 20:30:37 - PL1903DP-11
2023-07-19 20:32:15 - Error in offboarding operation. Exception: Cannot process argument transformation on parameter 'DeviceId'. Cannot convert value to type System.String.

**Comment by AleschaP** [comment] 2023-07-20 03:52
As a GA on the tenant, which additional roles are required?

2023-07-20 05:44:46 - Error occurred during search operation. Exception: Insufficient privileges to complete the operation.

Status: 403 (Forbidden)
ErrorCode: Authorization_RequestDenied
Date: 2023-07-20T03:44:47

**Comment by ugurkocde** [comment] 2023-07-20 07:37
> Hello :) Wow, nice work with new options :) That's my logs: 2023-07-19 20:29:24 - Window is loading... 2023-07-19 20:29:25 - Not connected to MS Graph 2023-07-19 20:29:25 - Window is loading... 2023-07-19 20:29:26 - Modules already installed. 2023-07-19 20:29:42 - Authentication Successful 2023-07-19 20:30:37 - PL1903DP-11 2023-07-19 20:32:15 - Error in offboarding operation. Exception: Cannot process argument transformation on parameter 'DeviceId'. Cannot convert value to type System.String.

Hi Dez, do you have twitter and can you contact me over there? @ugurkocde It will be easier to resolve it there due to the faster messaging on Twitter.


> As a GA on the tenant, which additional roles are required?
> 
> 2023-07-20 05:44:46 - Error occurred during search operation. Exception: Insufficient privileges to complete the operation.
> 
> Status: 403 (Forbidden) ErrorCode: Authorization_RequestDenied Date: 2023-07-20T03:44:47


I have added the required permissions to the ReadMe:

DeviceManagementManagedDevices.ReadWrite.All, 
DeviceManagementServiceConfig.ReadWrite.All

**Comment by Dez-Informatyk** [comment] 2023-07-20 13:47
Hey,
Sorry, but I haven't :p

**Comment by Dez-Informatyk** [comment] 2023-07-20 14:06
Ok, there is progress :)
When there is only 1 device, it works fine, it removed device from all systems :)
But when there are 2 devices, as @thiagobeier said, then I have a problem like the above.

**Comment by ugurkocde** [comment] 2023-07-20 20:04
@Dez-Informatyk alright, no problem. Lets try this here :) Can you tell me if the second devicename of the device you cant delete is present multiple times in AD and/or Intune? Also is it Azure AD Joined or Hybrid Joined?

**Comment by Dez-Informatyk** [comment] 2023-07-21 14:43
@ugurkocde One more thing - when I'm running the script, I need to run PS as a normal user (I don't have local admin role). If I try to run PS as admin, the authorization window is not opening in the browser.
2 different devices with the same situation, it's 2x in Azure, as AAD registered and Hybrid AAD joined; 1x Intune; 0x in autopilot)
That's old devices and the problem is probably on my side :?

**Comment by abill93** [comment] 2023-07-26 08:45
Hi 

I cant seem to find any serial or device name from using this, module is installed and I am connected. 
<img width="685" alt="Screenshot 2023-07-26 at 09 35 01" src="https://github.com/ugurkocde/IntuneOffboarding/assets/140597362/ede3c59e-4a4b-4c06-a11b-551131db02d7">


Any ideas?

**Comment by Dez-Informatyk** [comment] 2023-07-26 09:17
@abill93 
Did you check other devices? Check and send logs.

@ugurkocde 
I tried again with the new tool version, the result is in the attached file (the same device like above)
[IntuneOffboardingTool_Log.txt](https://github.com/ugurkocde/IntuneOffboarding/files/12170332/IntuneOffboardingTool_Log.txt)

**Comment by abill93** [comment] 2023-07-26 09:33
> @abill93 Did you check other devices? Check and send logs.
> 
> @ugurkocde I tried again with the new tool version, the result is in the attached file (the same device like above) [IntuneOffboardingTool_Log.txt](https://github.com/ugurkocde/IntuneOffboarding/files/12170332/IntuneOffboardingTool_Log.txt)

@Dez-Informatyk here is a screenshot stating the same: 
<img width="741" alt="Screenshot 2023-07-26 at 10 22 41" src="https://github.com/ugurkocde/IntuneOffboarding/assets/140597362/dfa82c1d-2f49-4c05-8d37-46164301370c"> I tried multiple devices serial and device name

**Comment by ugurkocde** [comment] 2023-07-26 19:38
Hey guys, working on a new way to check the requirements. This will help troubleshoot it even more. The main problem here is that I dont exactly know your environment so we will have to go step by step. 

@abill93 It lookls like the Get-MgDevice Command is not found. Could you please run 

`Install-Module -Name Microsoft.Graph.Identity.DirectoryManagement` and see if it fixes it?

@Dez-Informatyk your log is showing me that you search for serialnumber but the field is empty:

`filter=contains(serialNumber%2c%27%27)` equals to -> `$filter=contains(serialNumber,'')` where the serialNumber is empty.

**Comment by abill93** [comment] 2023-07-27 07:37
> Hey guys, working on a new way to check the requirements. This will help troubleshoot it even more. The main problem here is that I dont exactly know your environment so we will have to go step by step.
> 
> @abill93 It lookls like the Get-MgDevice Command is not found. Could you please run
> 
> `Install-Module -Name Microsoft.Graph.Identity.DirectoryManagement` and see if it fixes it?
> 
> @Dez-Informatyk your log is showing me that you search for serialnumber but the field is empty:
> 
> `filter=contains(serialNumber%2c%27%27)` equals to -> `$filter=contains(serialNumber,'')` where the serialNumber is empty.

Hi @ugurkocde I am still having issues same error: 
<img width="892" alt="Screenshot 2023-07-27 at 08 33 28" src="https://github.com/ugurkocde/IntuneOffboarding/assets/140597362/584375ff-e229-45b8-ae98-4afd40eb66e0">

The error on logs:
<img width="1343" alt="Screenshot 2023-07-27 at 08 34 30" src="https://github.com/ugurkocde/IntuneOffboarding/assets/140597362/68ecba53-0823-4d78-be4a-55ab42ea7e32">

Can I confirm this works with non autopilot devices? I enrol devices via provisioning packages not autopilot.

**Comment by Dez-Informatyk** [comment] 2023-07-28 08:14
> Hey guys, working on a new way to check the requirements. This will help troubleshoot it even more. The main problem here is that I dont exactly know your environment so we will have to go step by step.
> 
> @abill93 It lookls like the Get-MgDevice Command is not found. Could you please run
> 
> `Install-Module -Name Microsoft.Graph.Identity.DirectoryManagement` and see if it fixes it?
> 
> @Dez-Informatyk your log is showing me that you search for serialnumber but the field is empty:
> 
> `filter=contains(serialNumber%2c%27%27)` equals to -> `$filter=contains(serialNumber,'')` where the serialNumber is empty.

Hi @ugurkocde :)
When I'm trying with the device name, I get again:
2023-07-28 10:11:43 - Error in offboarding operation. Exception: Cannot process argument transformation on parameter 'DeviceId'. Cannot convert value to type System.String.

**Comment by barberj66** [comment] 2023-09-14 19:23
Great tool! I've found during some testing in my test tenant I am able to search fine via both device name and serial number however whilst using the device name I am able to also offboard the devices from Intune, AP and AAD without any issues if I try using the serial number to do the same thing whilst I search and can find the devices and see them when trying to offboard by Serial number I get an error saying device not found despite the search finding it OK.

Looking in the logs it give the error with the ending $filter=contains(serialNumber%2c%27%27)" which I think you mentioned earlier means there is no serial number present despite me being able to search and find the devices via serial number?

Just testing this with some throwaway VM's so the serial numbers are in the form 5018-7467-5402-3474-4941-1716-91 so not sure if the multiple - is causing some issue or what. Full error for one device I attempted is 

2023-09-14 21:10:31 - 5018-7467-5402-3474-4941-1716-91
2023-09-14 21:10:35 - Error in offboarding operation. Exception: {
  "_version": 3,
  "Message": "An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 349ddfe4-f986-4527-a5a8-d8f00088ca3e - Url: https://fef.msub06.manage.microsoft.com/DeviceEnrollmentFE_2308/StatelessDeviceEnrollmentFEService/deviceManagement/windowsAutopilotDeviceIdentities?api-version=2021-01-22&$filter=contains(serialNumber%2c%27%27)",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}

Status: 400 (BadRequest)
ErrorCode: BadRequest
Date: 2023-09-14T19:10:22

**Comment by egoodmanivi** [comment] 2023-09-28 14:46
> Great tool! I've found during some testing in my test tenant I am able to search fine via both device name and serial number however whilst using the device name I am able to also offboard the devices from Intune, AP and AAD without any issues if I try using the serial number to do the same thing whilst I search and can find the devices and see them when trying to offboard by Serial number I get an error saying device not found despite the search finding it OK.
> 
> Looking in the logs it give the error with the ending $filter=contains(serialNumber%2c%27%27)" which I think you mentioned earlier means there is no serial number present despite me being able to search and find the devices via serial number?
> 
> Just testing this with some throwaway VM's so the serial numbers are in the form 5018-7467-5402-3474-4941-1716-91 so not sure if the multiple - is causing some issue or what. Full error for one device I attempted is
> 
> 2023-09-14 21:10:31 - 5018-7467-5402-3474-4941-1716-91 2023-09-14 21:10:35 - Error in offboarding operation. Exception: { "_version": 3, "Message": "An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 349ddfe4-f986-4527-a5a8-d8f00088ca3e - Url: https://fef.msub06.manage.microsoft.com/DeviceEnrollmentFE_2308/StatelessDeviceEnrollmentFEService/deviceManagement/windowsAutopilotDeviceIdentities?api-version=2021-01-22&$filter=contains(serialNumber%2c%27%27)", "CustomApiErrorPhrase": "", "RetryAfter": null, "ErrorSourceService": "", "HttpHeaders": "{}" }
> 
> Status: 400 (BadRequest) ErrorCode: BadRequest Date: 2023-09-14T19:10:22

Hello, this same issue happened to me when searching for a device using serial number.  The device was retrieved fine but could not be deleted and showed the same error in the logs.  However, when I searched for the same device using the Devicename it was able to be deleted from Intune/AAD/Autopilot just fine.  So there may be something with the serialnumber verses devicename in the code.  Thanks

**Comment by ugurkocde** [comment] 2024-03-25 11:20
Hello guys @egoodmanivi, @barberj66, @superKlaver-nl, @Dez-Informatyk and @thiagobeier 

I am currently working on a complete rewrite. Most of the errors mentioned in this issue is because of the Graph cmdlets and timing errors. I am switching to Invoke-GraphRequest as well as support App Registrations for the authentication.

Closing this Issue for now but will release the new version ASAP.

**Closed as completed by ugurkocde** 2024-03-25 11:20 UTC
Labels: bug
